
/*
CREATE TABLE Users (
    UserID          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Username        VARCHAR(50) NOT NULL UNIQUE,
    PasswordHash    VARCHAR(255) NOT NULL,
    FullName        VARCHAR(100) NOT NULL,
    Role            VARCHAR(20) NOT NULL CHECK (Role IN ('Admin', 'Warden', 'Guard', 'Viewer')),
    Email           VARCHAR(100),
    Phone           VARCHAR(20),
    IsActive        BOOLEAN DEFAULT TRUE,
    CreatedAt       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt       TIMESTAMP
);

CREATE TABLE Locations (
    LocationID      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    LocationName    VARCHAR(100) NOT NULL,
    Type            VARCHAR(30) CHECK (Type IN ('Cell', 'Workshop', 'Dining', 'Yard', 'Hospital')),
    Capacity        INT NOT NULL,
    SecurityLevel   VARCHAR(20),
    IsActive        BOOLEAN DEFAULT TRUE,
    CreatedAt       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt       TIMESTAMP
);

CREATE TABLE Prisoners (
    PrisonerID          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FullName            VARCHAR(100) NOT NULL,
    DateOfBirth         DATE NOT NULL,
    Gender              VARCHAR(10) CHECK (Gender IN ('Male', 'Female', 'Other')),
    CrimeType           VARCHAR(100),
    RiskLevel           VARCHAR(20) CHECK (RiskLevel IN ('Low', 'Medium', 'High')),
    ProductivityScore   DECIMAL(5,2) DEFAULT 0,
    RehabHours          INT DEFAULT 0,
    CurrentLocationID   INT REFERENCES Locations(LocationID),
    SentenceStart       DATE,
    SentenceEnd         DATE,
    Status              VARCHAR(20) DEFAULT 'InPrison',
    CreatedAt           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt           TIMESTAMP
);

-- ==========================================
-- 2. KINH TẾ & LAO ĐỘNG
-- ==========================================

CREATE TABLE LaborProjects (
    ProjectID       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProjectName     VARCHAR(100) NOT NULL,
    RevenuePerHour  DECIMAL(10,2) NOT NULL,
    PriorityScore   INT DEFAULT 0,
    MaxWorkers      INT NOT NULL,
    RequiredSkills  VARCHAR(200),
    IsActive        BOOLEAN DEFAULT TRUE,
    CreatedAt       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt       TIMESTAMP
);

CREATE TABLE Shifts (
    ShiftID         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ShiftType       VARCHAR(30) NOT NULL,
    StartTime       TIME NOT NULL,
    EndTime         TIME NOT NULL,
    Capacity        INT NOT NULL,
    IsForStaff      BOOLEAN DEFAULT FALSE,
    CreatedAt       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt       TIMESTAMP
);

CREATE TABLE LaborAssignments (
    AssignmentID    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PrisonerID      INT NOT NULL REFERENCES Prisoners(PrisonerID),
    ProjectID       INT NOT NULL REFERENCES LaborProjects(ProjectID),
    AssignmentDate  DATE NOT NULL,
    HoursAssigned   DECIMAL(5,2) NOT NULL,
    CreatedAt       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt       TIMESTAMP
);

CREATE TABLE DailyPerformance (
    PerformanceID   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PrisonerID      INT NOT NULL REFERENCES Prisoners(PrisonerID),
    ProjectID       INT NOT NULL REFERENCES LaborProjects(ProjectID),
    WorkDate        DATE NOT NULL,
    Productivity    DECIMAL(5,2) NOT NULL,
    Notes           TEXT, -- Dùng TEXT cho linh hoạt
    CreatedAt       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ==========================================
-- 3. LẬP LỊCH & AI
-- ==========================================

CREATE TABLE Schedules (
    ScheduleID      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PrisonerID      INT NOT NULL REFERENCES Prisoners(PrisonerID),
    ProjectID       INT REFERENCES LaborProjects(ProjectID),
    LocationID      INT REFERENCES Locations(LocationID),
    ShiftID         INT NOT NULL REFERENCES Shifts(ShiftID),
    StartTime       TIMESTAMP NOT NULL,
    EndTime         TIMESTAMP NOT NULL,
    AlgorithmTag    VARCHAR(20) NOT NULL CHECK (AlgorithmTag IN ('Greedy', 'Genetic', 'OR-Tools')),
    Status          VARCHAR(20) DEFAULT 'Active',
    CreatedAt       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt       TIMESTAMP
);

CREATE TABLE SchedulingConfigs (
    ConfigID        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AlgorithmName   VARCHAR(20) NOT NULL,
    WeightEconomy   DECIMAL(5,2) DEFAULT 0.4,
    WeightSecurity  DECIMAL(5,2) DEFAULT 0.3,
    WeightRehab     DECIMAL(5,2) DEFAULT 0.3,
    LastRun         TIMESTAMP,
    Parameters      JSONB, -- Chuyển sang JSONB để tối ưu cho AI/Data Engineer
    CreatedAt       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt       TIMESTAMP
);

-- ==========================================
-- 4. TƯƠNG TÁC & PHÁP LÝ
-- ==========================================

CREATE TABLE Visits (
    VisitID         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PrisonerID      INT NOT NULL REFERENCES Prisoners(PrisonerID),
    VisitorName     VARCHAR(100) NOT NULL,
    VisitDate       TIMESTAMP NOT NULL,
    Status          VARCHAR(20) DEFAULT 'Pending',
    ApprovedBy      INT REFERENCES Users(UserID),
    Notes           TEXT,
    CreatedAt       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt       TIMESTAMP
);

CREATE TABLE Incidents (
    IncidentID      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PrisonerID      INT NOT NULL REFERENCES Prisoners(PrisonerID),
    IncidentDate    TIMESTAMP NOT NULL,
    IncidentType    VARCHAR(100),
    Severity        VARCHAR(20) CHECK (Severity IN ('Low', 'Medium', 'High')),
    PenaltyPoints   INT DEFAULT 0,
    Description     TEXT,
    CreatedBy       INT REFERENCES Users(UserID),
    CreatedAt       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Thông báo hoàn tất (PostgreSQL style)
DO $$ 
BEGIN 
    RAISE NOTICE '✅ Đã xóa các bảng cũ và tạo lại 11 bảng thành công!'; 
END $$;


*/

select * from Prisoners;